api_version = "2024-01"

[[extensions]]
handle = "shipping-discount-extension-2"
name = "t:name"
description = "t:description"
type = "function"
scopes = "write_products, write_discounts"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
